version: "3.8"

services:
  app1:
    build: .
    hostname: demian-lee-app1
    environment:
      - PORT=8080

  app2:
    build: .
    hostname: demian-lee-app2
    environment:
      - PORT=8080

  loadbalancer:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
